networks:
  dev:

services:
  db:
    image: postgres:latest
    container_name: db_s2t
    command: -p 1200
    expose:
      - 1200
    env_file:
      - ./s2t_system/.env
    networks:
      - dev

  backend:
    build:
      context: ./s2t_system
    env_file:
        - ./s2t_system/.env
    container_name: s2t
    command: ["/s2t_system/docker/app.sh"]
    ports:
      - 7777:8000
    depends_on:
      - db
      - redis
    networks:
      - dev

  redis:
    image: redis:latest
    container_name: redis_app
    networks:
      - dev
    volumes:
      - ./redisdata:/data
    ports:
      - "1300:1300"
    expose:
      - 1300
    restart: unless-stopped
    tty: true
    stdin_open: true

  celery:
    build:
      context: ./s2t_system
    container_name: celery
    command: celery -A src.tasks worker -l info
    env_file:
      - ./s2t_system/.env
    depends_on:
      - redis
      - db
      - backend
    networks:
      - dev

  flower:
    build:
      context: ./s2t_system
    container_name: flower
    command: celery -A src.tasks flower
    depends_on:
      - redis
      - celery
      - backend
    env_file:
      - ./s2t_system/.env
    networks:
      - dev
    ports:
      - 5555:5555