networks:
  dev:

services:
  db:
    image: postgres:latest
    container_name: db_s2t
    command: -p 1200
    expose:
      - 1200
    env_file:
      - ./s2t_system/.env
    networks:
      - dev

  backend:
    build:
      context: ./s2t_system
    env_file:
        - ./s2t_system/.env
    container_name: s2t
    command: ["/s2t_system/docker/app.sh"]
    ports:
      - 7777:8000
    depends_on:
      - db
      - redis
    networks:
      - dev

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - dev
    volumes:
      - ./redisdata:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    ports:
      - "1300:1300"
    expose:
      - 1300
    restart: unless-stopped
    tty: true
    stdin_open: true

  celery:
    build:
      context: ./s2t_system
    container_name: celery
    command: ["celery", "--app=src.tasks:celery", "worker", "-l", "INFO"]
    env_file:
      - ./s2t_system/.env
    depends_on:
      - redis
      - db
      - backend
    networks:
      - dev

  flower:
    build:
      context: ./s2t_system
    container_name: flower
    command: ["celery", "--app=src.tasks:celery", "flower"]
    depends_on:
      - redis
      - celery
      - backend
    env_file:
      - ./s2t_system/.env
    networks:
      - dev
    ports:
      - 5555:5555